#!/usr/bin/env python3
"""Experiment probe for #17: which spoken-Korean reading of a 순환소수 is
unambiguous BY EAR?

NOT a pipeline stage (see #15 — this is eval/experiment tooling, kept apart
from the image→wav chain on purpose). It generates audio for competing
readings of repeating decimals so a human can A/B listen and judge. The
script never picks a winner: that is decided by listening, not logic.

A reading of 0.12̇3̇ (= 0.1232323...) must convey three things or the listener
hears a WRONG NUMBER:
  1. which digits repeat (the 순환마디 / repetend),
  2. that they repeat infinitely,
  3. where the repetend STARTS ("1" does not repeat here).
The killer test is the minimal pair
  case 3   0.12̇3̇  = 0.1232323...  (repetend 23)
  case 5   0.1̇23̇   = 0.123123...   (repetend 123)
— same digits, different repetend start. A reading that cannot keep these two
apart by ear FAILS, whatever else it does well.

Each reading style is a function (integer_part, non_repeating, repetend) ->
Korean text, so styles generalize across every case instead of being
hardcoded per example. Add new candidates to READINGS below.

Predictions go in docs/findings/17_repeating_decimals.md BEFORE listening
(the file is scaffolded on first run and never overwritten).

Usage:
  python dot_reading_probe.py                 # scaffold findings + synth all wavs
  python dot_reading_probe.py --dry-run       # print texts/table, no Azure calls
  python dot_reading_probe.py --voice ko-KR-InJoonNeural --out ./audio/exp17

Credentials: reuses tts_probe.py's loader (AZURE_SPEECH_KEY +
AZURE_SPEECH_ENDPOINT / AZURE_SPEECH_REGION from env or .env). Never hardcoded.
"""
import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).parent
FINDINGS = ROOT / "docs" / "findings" / "17_repeating_decimals.md"

DIGIT_KO = {"0": "영", "1": "일", "2": "이", "3": "삼", "4": "사",
            "5": "오", "6": "육", "7": "칠", "8": "팔", "9": "구"}


def words(digits):
    """Digit string -> compact Sino-Korean digit reading ('23' -> '이삼')."""
    return "".join(DIGIT_KO[d] for d in digits)


def _i_ga(word):
    """Subject particle 이/가 by 받침 of the last syllable ('삼'->이, '사'->가)."""
    code = ord(word[-1]) - 0xAC00
    return "이" if 0 <= code < 11172 and code % 28 else "가"


def _head(integer, pre):
    """Shared '영 점 [일]' prefix: integer part, 점, then non-repeating digits."""
    return f"{words(integer)} 점" + (f" {words(pre)}" if pre else "")


# ---------------------------------------------------------------- readings
# Each: (integer_part, non_repeating_digits, repetend_digits) -> Korean text.
# These are CANDIDATES under test — do not treat any of them as the answer.

def read_a(integer, pre, rep):
    """A. Name-repetend-first: '순환소수 영 점 일, 순환마디 이삼'."""
    return f"순환소수 {_head(integer, pre)}, 순환마디 {words(rep)}"


def read_b(integer, pre, rep):
    """B. Boundary-marker: '영 점 일 다음 이삼이 반복' — explicit start marker."""
    r = words(rep)
    return f"{_head(integer, pre)} 다음 {r}{_i_ga(r)} 반복"


def read_c(integer, pre, rep):
    """C. Repeat-then-label: '영 점 일 이삼 이삼 반복' — the naive candidate,
    expected to fail on partial repetends (that is what the test is for)."""
    r = words(rep)
    return f"{_head(integer, pre)} {r} {r} 반복"


READINGS = {
    "A-name-first": read_a,
    "B-boundary": read_b,
    "C-repeat-twice": read_c,
    # D: add the next candidate here — one function, all five cases come free.
    # e.g. "D-voice-switch": a reading where the repetend digits are spoken by
    # the opposite-gender voice (would need the SSML path, cf. speak.js radicals)
}

# --------------------------------------------------------------- test cases
# (id, printed form, integer part, non-repeating digits, repetend, note)
CASES = [
    ("case1", "0.3̇",   "0", "",  "3",   "0.333...      single digit"),
    ("case2", "0.2̇4̇",  "0", "",  "24",  "0.242424...   whole fractional part repeats"),
    ("case3", "0.12̇3̇", "0", "1", "23",  "0.1232323...  CRITICAL: the 1 does NOT repeat"),
    ("case4", "0.16̇7̇", "0", "1", "67",  "0.1676767...  partial, longer"),
    ("case5", "0.1̇23̇",  "0", "",  "123", "0.123123...   ambiguity foil for case3"),
]

# ------------------------------------------------------- prediction scaffold

TEMPLATE = """\
# #17 — What should a 순환소수 sound like? (experiment log)

Generated by dot_reading_probe.py. **Fill in every "Prediction:" line BEFORE
listening to any audio.** A wrong prediction written down is worth more than a
right result unrecorded.

The pass/fail test: case 3 (0.12̇3̇, repetend 23) vs case 5 (0.1̇23̇, repetend
123). If a reading cannot be told apart by ear between those two, it fails —
the listener heard a wrong number, not an awkward one.

> ⚠ Convention check (do not skip): the 순환마디-naming convention used in
> reading A has NOT been verified against an actual Korean 중2 textbook —
> check a real textbook (or teacher) before adopting any reading that names it.

## Reading A — name-repetend-first ("순환소수 영 점 일, 순환마디 이삼")

Prediction:
Result after listening:

## Reading B — boundary-marker ("영 점 일 다음 이삼이 반복")

Prediction:
Result after listening:

## Reading C — repeat-then-label ("영 점 일 이삼 이삼 반복")

Prediction:
Result after listening:

## Overall verdict

Which reading (if any) survives the case3-vs-case5 pair:
What surprised me:
"""


def scaffold_findings():
    if FINDINGS.exists():
        print(f"[findings] {FINDINGS} exists — leaving your predictions alone")
        return
    FINDINGS.parent.mkdir(parents=True, exist_ok=True)
    FINDINGS.write_text(TEMPLATE, encoding="utf-8")
    print(f"[findings] scaffolded {FINDINGS}")


# ------------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser(
        description="Generate A/B audio for candidate 순환소수 readings (#17).")
    ap.add_argument("--out", default="./audio/exp17", help="wav folder (default ./audio/exp17)")
    ap.add_argument("--voice", default="ko-KR-SunHiNeural")
    ap.add_argument("--dry-run", action="store_true", help="print texts, no Azure calls")
    a = ap.parse_args()

    scaffold_findings()  # BEFORE any audio exists

    rows = []  # (case_id, printed, style, text, filename)
    for cid, printed, integer, pre, rep, _note in CASES:
        for style, fn in READINGS.items():
            rows.append((cid, printed, style, fn(integer, pre, rep),
                         f"{cid}-{style}.wav"))

    failures = 0
    if not a.dry_run:
        from tts_probe import make_config, synth
        out = Path(a.out)
        out.mkdir(parents=True, exist_ok=True)
        cfg = make_config(a.voice)
        for cid, printed, style, text, fname in rows:
            path = out / fname
            try:
                ok, detail = synth(cfg, path, text=text)
            except Exception as e:  # one failure must not kill the batch
                ok, detail = False, f"{type(e).__name__}: {e}"
            failures += not ok
            print(f"  [{'ok' if ok else 'FAIL':>4}] {fname:<28} {detail}")

    print(f"\n{'case':<7} {'printed':<8} {'reading':<16} {'file':<28} text")
    print("-" * 100)
    for cid, printed, style, text, fname in rows:
        print(f"{cid:<7} {printed:<8} {style:<16} {fname:<28} {text}")
    print("-" * 100)
    for cid, printed, _i, _p, _r, note in CASES:
        print(f"  {cid}: {printed:<8} {note}")

    out = Path(a.out)
    print(f"""
{'=' * 72}
LISTEN IN THIS ORDER — the case3 vs case5 pair IS the test
{'=' * 72}""")
    for style in READINGS:
        print(f"\n  {style}:  0.12̇3̇ (repetend 23)  vs  0.1̇23̇ (repetend 123)")
        print(f"    afplay '{out / f'case3-{style}.wav'}'")
        print(f"    afplay '{out / f'case5-{style}.wav'}'")
    print("""
Then the sanity cases (1, 2, 4) per reading, in any order.

>>> Fill in predictions in {f} BEFORE listening to the audio. <<<
""".format(f=FINDINGS))
    if failures:
        sys.exit(f"{failures} synthesis call(s) FAILED — see rows above.")


if __name__ == "__main__":
    main()
